stages:
  train:
    cmd: python src/train.py --config-name=train experiment=catdog_ex trainer.max_epochs=5
    deps:
    - configs/experiment/catdog_ex.yaml
    - data/cats_and_dogs_filtered
    - src/train.py
  test:
    cmd: python src/evaluate.py --config-name=eval experiment=catdog_ex_eval.yaml
    deps:
    - configs/experiment/catdog_ex_eval.yaml
    - src/evaluate.py
  infer:
    cmd: python src/infer.py --config-name=infer experiment=catdog_ex_eval.yaml
    deps:
    - configs/experiment/catdog_ex_eval.yaml
    - src/infer.py
  report_generation:
    cmd: python src/utils/model_metrics.py
