defaults:
  - _self_
  - data: dogbreed_modules # assuming you have a dogbreed.yaml in configs/data/
  - model: dogbreed_classifier # assuming you have a dogbreed_classifier.yaml in configs/model/
  - paths: default
  - hydra: default
  - logger: null
  - callbacks: default

task_name: "evaluate"

ckpt_path: null # This should be specified when running the script

data:
  # Any specific configurations for evaluation data

model:
  # Any specific configurations for the model during evaluation

hydra:
  run:
    dir: ${paths.log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
