defaults:

  - _self_

  - model: dogbreed_classifier

  - paths: default

  - hydra: default


task_name: infer

paths:
  root_dir:${oc.env:PROJECT_ROOT,${hydra:runtime.cwd}}
  #output_dir: ${paths.root_dir}/infer_results

#ckpt_path: /workspace/checkpoints/epoch_best.ckpt
ckpt_path: ${paths.root_dir}/checkpoints/epoch_best.ckpt
num_images: ${num_classes} # Number of images to process

# Define input and output folders
input_folder: ${paths.root_dir}/infer_images
output_folder: ${paths.root_dir}/infer_results

# List of class names (dog breeds) in the order of model's output
class_names:
  - Labrador Retriever
  - German Shepherd
  - Golden Retriever
  - Bulldog
  - Beagle
  - Boxer
  - Dachshund
  - Poodle
  - Rottweiler
  - Yorkshire Terrier

  # Add more breed names as needed

num_classes: ${num_classes}  # or whatever number of classes you have
model: ${model/dogbreed_classifier}

hydra:
  run:
    dir: ${paths.log_dir}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
