# Note you can also directly use "GDRIVE_CREDENTIALS_DATA" as env variable and pull it
- name: Create credentials.json
env:
GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
run: |
echo $GDRIVE_CREDENTIALS_DATA > credentials.json
- name: Modify dvc Remote
run: |
dvc remote modify - local myremote credentialpath credentials.json
- name: dvc Pull Data
run: |
dvc pull -v