name: DVC - Google Cloud Storage bucket Workflow
on:
  workflow_dispatch:

jobs:
  dvc-gcs-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Packages
        run: pip install -r requirements.txt

      # Note you can also directly use "GDRIVE_CREDENTIALS_DATA" as env variable and pull
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > credentials.json

      - name: Modify DVC Remote
        run: |
          dvc remote modify --local gcloud credentialpath credentials.json

      - name: DVC Pull Data
        run: |
          dvc pull -v